// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    Drag: typeof import('./src/components/Drag.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Form: typeof import('./src/components/Form.vue')['default']
  }
}

export { }
